name: "Build Unsigned"

on: workflow_dispatch

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-26"
            args: "--target aarch64-apple-darwin"
            target: "aarch64-apple-darwin"
          # - platform: "macos-latest"
          #   args: "--target x86_64-apple-darwin"
          #   target: "x86_64-apple-darwin"

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      sign-binaries: false
      upload-artifacts: true
      asset-prefix: "handy-unsigned"
